import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "semantic-ui-css/semantic.min.css";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UPSC Notes & Mock Tests",
  description: "Generated by create next app",
};

// pdfjs.GlobalWorkerOptions.workerSrc = new URL(
//   "pdfjs-dist/build/pdf.worker.min.js",
//   import.meta.url
// ).toString();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={open_sans.className}>{children}</body>
    </html>
  );
}
